apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-api-config
data:
  ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=HealthMedDb;User Id=sa;Password=NovaSenhaForte123;TrustServerCertificate=True"