apiVersion: v1
kind: ConfigMap
metadata:
  name: schedule-api-config
data:
  ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=HealthMedDb;User Id=sa;Password=NovaSenhaForte123;TrustServerCertificate=True"
  RabbitMQ__Host: rabbitmq
  RabbitMQ__Port: "5672"
  RabbitMQ__Username: guest
  RabbitMQ__Password: guest